"""Subsystem models.

Each subsystem implements the SubsystemModel protocol: take the satellite's
current geometric state plus the subsystem's previous internal state, return
the new internal state and a dict of telemetry channels for this tick.

Integration is forward Euler. Step size is dt = sim_clock.tick_seconds.
At 1 Hz the error is negligible for the dynamics here (SoC changes on
minute timescales, temperature on hour timescales).

Coupling
--------
The two models below are coupled through the SatelliteState:
- EPS reads `sun_vector_eci` and `eclipsed` to compute generated power.
- Thermal reads `eclipsed` to gate solar heat input.

They are not coupled to each other in this iteration (the thermal model
doesn't draw from the battery; the EPS doesn't depend on temperature).
That coupling — battery efficiency vs. temperature, heater power vs.
cold soak — is a later refinement.

Earth IR
--------
The thermal model includes a continuous Earth-infrared heat input
(~100 W). This is present whether the satellite is sunlit or eclipsed;
it's the reason eclipse temperatures don't collapse toward deep-space
values. A more refined model would compute the Earth view factor from
altitude and attitude; we use a fixed value.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from orbit_ops.sim.satellite import SatelliteState
from orbit_ops.sim.subsystem_params import CONST, EPS, THERMAL


@dataclass(frozen=True, slots=True)
class EpsState:
    """Internal state of the electrical power subsystem."""

    soc: float
    """Battery state-of-charge, 0..1."""


@dataclass(frozen=True, slots=True)
class ThermalState:
    """Internal state of the thermal subsystem."""

    temperature_k: float
    """Bus temperature (K)."""


@dataclass(frozen=True, slots=True)
class EpsTelemetry:
    solar_power_w: float
    """Power generated by the solar array right now (W)."""
    bus_power_w: float
    """Power drawn by the bus right now (W)."""
    net_power_w: float
    """solar_power_w - bus_power_w. Positive = charging, negative = discharging."""
    battery_soc: float
    """Same as EpsState.soc, surfaced for telemetry stream."""
    battery_charge_wh: float
    """Absolute charge in the battery (Wh). Convenience for plotting."""


@dataclass(frozen=True, slots=True)
class ThermalTelemetry:
    bus_temperature_k: float
    bus_temperature_c: float
    """Same as bus_temperature_k - 273.15. Convenience for humans."""
    solar_heat_input_w: float
    earth_ir_input_w: float
    radiative_heat_output_w: float
    net_heat_w: float
    """solar + internal - radiated. Positive = warming, negative = cooling."""


# ---------- EPS ----------


def eps_initial_state() -> EpsState:
    return EpsState(soc=EPS.initial_soc)


def _solar_array_power(geo: SatelliteState) -> float:
    """Power generated by the solar array (W).

    Simplification: array normal is aligned with the satellite-to-sun direction
    when sunlit. (A real attitude control system would point the array; here we
    assume it does, perfectly.) Power = irradiance * area * efficiency, gated
    by the eclipse flag.
    """
    if geo.eclipsed:
        return 0.0
    return EPS.solar_flux_w_m2 * EPS.array_area_m2 * EPS.array_efficiency


def _bus_load(geo: SatelliteState) -> float:
    """Bus power draw (W). Lower during eclipse (payload off)."""
    return EPS.eclipse_load_w if geo.eclipsed else EPS.bus_load_w


def eps_step(geo: SatelliteState, prev: EpsState, dt_s: float) -> tuple[EpsState, EpsTelemetry]:
    """Advance the EPS one tick. Forward Euler on battery SoC."""
    p_gen = _solar_array_power(geo)
    p_load = _bus_load(geo)
    p_net = p_gen - p_load  # W

    # Convert net power to SoC change. Battery capacity is in Wh; dt in seconds.
    delta_wh = p_net * (dt_s / 3600.0)
    delta_soc = delta_wh / EPS.battery_capacity_wh
    soc_next = float(np.clip(prev.soc + delta_soc, EPS.battery_min_soc, EPS.battery_max_soc))

    telemetry = EpsTelemetry(
        solar_power_w=p_gen,
        bus_power_w=p_load,
        net_power_w=p_net,
        battery_soc=soc_next,
        battery_charge_wh=soc_next * EPS.battery_capacity_wh,
    )
    return EpsState(soc=soc_next), telemetry


# ---------- Thermal ----------


def thermal_initial_state() -> ThermalState:
    return ThermalState(temperature_k=THERMAL.initial_temperature_k)


def _solar_heat_input(geo: SatelliteState) -> float:
    """Solar heat absorbed by the bus (W). Zero during eclipse."""
    if geo.eclipsed:
        return 0.0
    return EPS.solar_flux_w_m2 * THERMAL.cross_section_m2 * THERMAL.absorptivity


def _radiative_heat_output(temperature_k: float) -> float:
    """Heat radiated to space (W) by Stefan-Boltzmann.

    Subtract the deep-space background (negligibly small at 2.7 K, but
    included for completeness).
    """
    t4 = temperature_k**4 - CONST.deep_space_temperature_k**4
    return CONST.stefan_boltzmann_w_m2_k4 * THERMAL.emissivity * THERMAL.radiating_area_m2 * t4


def thermal_step(
    geo: SatelliteState, prev: ThermalState, dt_s: float
) -> tuple[ThermalState, ThermalTelemetry]:
    """Advance the thermal model one tick. Forward Euler on temperature.

    dT/dt = (Q_solar + Q_internal - Q_radiated) / (m * c)
    """
    q_sun = _solar_heat_input(geo)
    q_int = THERMAL.internal_dissipation_w
    q_earth = THERMAL.earth_ir_w
    q_rad = _radiative_heat_output(prev.temperature_k)
    q_net = q_sun + q_int + q_earth - q_rad  # W

    heat_capacity = THERMAL.mass_kg * THERMAL.specific_heat_j_kg_k  # J/K
    dt_k = q_net * dt_s / heat_capacity
    t_next = prev.temperature_k + dt_k

    telemetry = ThermalTelemetry(
        bus_temperature_k=t_next,
        bus_temperature_c=t_next - 273.15,
        solar_heat_input_w=q_sun,
        earth_ir_input_w=q_earth,
        radiative_heat_output_w=q_rad,
        net_heat_w=q_net,
    )
    return ThermalState(temperature_k=t_next), telemetry
